-- THESE ARE SQL QUERIES TO INSERT SOME DUMMY DATA IN THE DATABASE. THESE SHOULD BE RUN ONLY AFTER
-- RUNNING PRISMA MIGRATE FROM THE COMMAND LINE

-- INSERT DATA INTO THE ADMIN TABLE.
-- NOTE THE PASSWORD BEING STORED HERE IS JUST FOR TESTING AND AUTHENTICATION WON'T WORK WITH THE PASSWORD.
INSERT INTO Admin
VALUES ('TEST_ADMIN', 'TEST_PASSWORD', 'TEST_ADMIN', 'testadmin@test.com', '9876543210', 1, 'TEST_SALT',
        'TEST_TOKEN');

-- INSERT DATA INTO DEPARTMENT TABLE WITH TEST_ADMIN AS HOD.
INSERT INTO Department
VALUES ('TEST_DEPT', 'TEST_DEPARTMENT', (SELECT username FROM Admin WHERE username = 'TEST_ADMIN'));

-- INSERT BRANCH DATA
INSERT INTO Branch
VALUES ('TEST_DEPT_TEST_BRANCH', 'TEST_BRANCH', (SELECT id FROM Department WHERE id = 'TEST_DEPT'));

-- INSERT SESSION DATA
INSERT INTO Session
VALUES ('2020-21',
        (SELECT id FROM Branch WHERE id = 'TEST_DEPT_TEST_BRANCH'), 2020, 1, 1, 'July', 'December',
        (SELECT id FROM Department WHERE id = 'TEST_DEPT'));

-- INSERT PhD STUDENT DATA
INSERT INTO Student
VALUES ('TEST_REG', 'PhD', 1, NULL, NULL, NULL, NULL, NULL, (SELECT id FROM Session WHERE id = '2020-21'),
        (SELECT id FROM Branch WHERE id = 'TEST_DEPT_TEST_BRANCH'),
        (SELECT id FROM Department WHERE id = 'TEST_DEPT'),
        'TEST_PASSWORD',
        'TEST_SALT');

-- INSERT MTech STUDENT DATA
INSERT INTO Student
VALUES ('TEST_REG_MTECH', 'MTech', 1, NULL, NULL, NULL, NULL, NULL, (SELECT id FROM Session WHERE id = '2020-21'),
        (SELECT id FROM Branch WHERE id = 'TEST_DEPT_TEST_BRANCH'),
        (SELECT id FROM Department WHERE id = 'TEST_DEPT'),
        'TEST_PASSWORD',
        'TEST_SALT');

-- INSERT ACADEMIC INFORMATION
INSERT INTO AcademicInformation
VALUES ('TEST_REG', 'OBC', 'Atheist', 'INDIAN', 'teststudent@test.com', 'TEST_PASSWORD', DATE('1995-01-01'),
        'TEST_FATHER');
INSERT INTO AcademicInformation
VALUES ('TEST_REG_MTECH', 'OBC', 'Atheist', 'INDIAN', 'teststudent@test.com', 'TEST_PASSWORD', DATE('1995-01-01'),
        'TEST_FATHER');

-- INSERT INTO FINANCIAL INFORMATION
INSERT INTO FinancialInformation
VALUES ('TEST_REG', 'TEST_BANK', 'TEST_ACC', 'TEST_IFSC', 'TEST_BRANCH');
INSERT INTO FinancialInformation
VALUES ('TEST_REG_MTECH', 'TEST_BANK', 'TEST_ACC', 'TEST_IFSC', 'TEST_BRANCH');